function txt_plastic() { //amogus
	
	msg = [
	
	txt("* heya."),
	txt("* ... Huh?"),
	txt("* looks like ya fell asleep, right? why not just do that in bed like a normal person?"),
	txt("* Oh crap! I was writing an essay due tomorrow, and I must have fell asleep instead of finishing it..."),
	txt("* tsk. shoulda done it sooner instead of procrastinating in dream land!"),
	txt("* at least ya got me around to help."),
	txt("* What even are you, if I might ask? Like, I'm... pretty sure my TV isn't supposed to be talking to me?"),
	txt("* tvs talk all the time though?"),
	txt("* Not like a sentient creature, though... They usually don't try to stare at me creepily either."),
	txt("* never watched a good horror film then! might be worth spicing up your taste a bit."),
	txt("* what am I, though? that's a good question! I can't be sure myself."),
	txt("* Do you at least have a name?"),
	txt("* nope. call me whatever ya want lady."),
	txt("* Okay... How about, uhm, Gizmo?"),
	txt("* seems a bit generic but alright I guess."),
	txt("* No you're right, that's like a Renko-tier name. I can do better!"),
	txt("* How about Sokrates? Surely that has a nice ring to it."),
	txt("* ye sure, let's go with that."),
	txt("* So uh... What exactly are you doing here, again?"),
	txt("* keepin an EYE on ya, of course. what else?"),
	txt("* I... Okay? I don't think I really need anyone else to watch over me, like just having Renko's perfectly fine."),
	txt("* Then again, maybe I'm just hallcinating you right now."),
	txt("* nah man. I'm the real deal. trust me. ya already well aware of the truths you can see, aren't ya?"),
	txt("* Yes. Although the fact you know this much about me is kind of disturbing?"),
	txt("* hey now! I'm not a stalker! and I don't know everything about ya either!"),
	txt("* like, I don't know what ya social security number is for instance! or ya favorite color!"),
	txt("* G-Good???"),
	txt("* And it's purple, for reference."),
	txt("* ahhhh okie dokie."),
	txt("* oh, and while I'm asking questions here, what is that essay ya writing over there. must be boring if you went snoozy-doozy."),
	txt("* Uhm. It's not quite boring, I've just felt really exhausted recently. I've barely slept the past 24 hours."),
	txt("* ah. that'd explain a few things."),
	txt("* Listen. I promise I'm trying to take care of myself here! It's just..."),
	txt("* This is one of the final essays for my psychology major, and I really want to do it right!"),
	txt("* So it's, well, pretty scary to think of what might happen if I fail it."),
	txt("* And it's always been on my mind for weeks. It just feels... suffocating, I guess."),
	txt("* well, maribel hearn. want some of my honest advice? it might help."),
	txt("* Uh... sure."),
	txt("* well. first off, maybe ya shouldn't be placing your expectations so high, ya know?"),
	txt("* don't get me wrong I know it's stressful and all but maybe you're making a bigger deal out of this than you need to."),
	txt("* I don't know. My future could literally depend on this paper..."),
	txt("* nah. don't sweat it kid, it's not gonna be the end of the world if ya fail."),
	txt("* like, if you asked me, I think it's already pretty obvious you're useless, so what's really gonna change?"),
	txt("* ..."),
	txt("* I mean, you've always been an utter freak to people, and the unlucky few willing to put up with you only just get dragged into your problems."),
	txt("* you hate your own reflection in the mirror, and rightfully so. I'd hate those disgusting eyes of yours too."),
	txt("* pupils that see the void and everything forgotten and everything you want to be and never will be."),
	txt("* pupils that see the one person you love, that you know you're just going to drag down with you."),
	txt("* and you're going to lose them one day. and you're going to hate it. you're going to scream and cry and wonder why it all had to end."),
	txt("* and then? you'll be all alone. alone with nothing but your sick, twisted, mi-"),
	// bye bye tv lmao
	txt("* ..."),
	txt("* You know, I really thought I buried you awhile ago."),
	txt("* Maybe it was never that simple..."),
	txt("* Merry?"),
	txt("* O-Oh. Hi, Renko."),
	txt("* ... Did you happen to uhm, see any of that."),
	txt("* Not really. I woke up, wondered where you went, and came over to see you... unplugging our television for some reason?"),
	txt("* But you seem really shaken up. I'm guessing you must have found a boundary there? Usually those don't attach themselves to technology..."),
	txt("* I saw... a spectre of sorts, of times where I wasn't as kind to myself."),
	txt("* Of times before I met you."),
	txt("* Do... Do you want to talk about it?"),
	txt("* No. I don't. It's better off being forgotten anyway."),
	txt("* My self-esteem... isn't as bad as it used to be, and I have you to love, and to remind me that I'm loved."),
	txt("* I don't have to burden myself with all of that baggage anymore."),
	txt("* You know, Merry. You taught me through our explorations that sometimes... fantasies really are scary, actually."),
	txt("* And maybe... Maybe the worst fantasies are the ones we conjure up about ourselves."),
	txt("* When at the end of the day, we don't have to listen to a voice inside our head telling us we aren't worth something."),
	txt("* We just have to stay determined to turn our dreams into reality. Like you'd always say."),
	txt("* Yeah. Exactly."),
	txt("* And you'll ace that essay, damn it. You know I have your back."),
	txt("* Thanks, Renko. I'll try my best."),
	txt("* I know you will."),
	txt("* Now, let's get back to bed, okay? This essay is tomorrow's problem to worry about now."),
	txt("* Huh? But-"),
	txt("* No buts! Only cuddles. Cuddles are more important and you know it."),
	txt("* ... Tch. You know me so well."),
	txt("* Fine. Let's go to bed then."),
	txt("* And thanks again for checking on me, Renko. I love you."),
	txt("* Love you too, Merry."),
	// the end!
	
	];
	
	endevent = function() { // this should send the player back to the title screen instead.
		log("GAME OVER, MAN!");
		//game_end();
		startpattern("Midnight Alarm");
	};
}