function txt_plastic() { //amogus
	
	msg = [
    
    btxt( [s_plastic1],),
	txt("* heya.", TV.NEUTRAL,SPRITEPOS.CENTER, function() {music_set(mus.connection)}),
	txt("* ... Huh?", MERRY.NEUTRAL),
	txt("* looks like ya fell asleep, right? why not just do that in bed like a normal person?", TV.NEUTRAL),
	txt("* Oh crap! I was writing an essay due tomorrow, and I must have fell asleep instead of finishing it...", MERRY.NEUTRAL),
	txt("* tsk. shoulda done it sooner instead of procrastinating in dream land!", TV.NEUTRAL),
	txt("* at least ya got me around to help.", TV.NEUTRAL),
	txt("* What even are you, if I might ask?", MERRY.NEUTRAL), 
	txt("* Like, I'm... pretty sure my TV isn't supposed to be talking to me?", MERRY.NEUTRAL),
	txt("* tvs talk all the time though?", TV.NEUTRAL),
	txt("* Not like a sentient creature, though... They usually don't try to stare at me creepily either.", MERRY.NEUTRAL),
	txt("* never watched a good horror film then! might be worth spicing up your taste a bit.", TV.NEUTRAL),
	txt("* what am I, though? that's a good question! I can't be sure myself.", TV.NEUTRAL),
	txt("* Do you at least have a name?", MERRY.NEUTRAL),
	txt("* nope. call me whatever ya want lady.", TV.NEUTRAL),
	txt("* Okay... How about, uhm, Gizmo?", MERRY.NEUTRAL),
	txt("* seems a bit generic but alright I guess.", GIZMO.NEUTRAL),
	txt("* No you're right, that's like a Renko-tier name. I can do better!", MERRY.NEUTRAL),
	txt("* How about Sokrates? Surely that has a nice ring to it.", MERRY.NEUTRAL),
	txt("* ye sure, let's go with that.", SOKRATES.NEUTRAL),
	txt("* So uh... What exactly are you doing here, again?", MERRY.NEUTRAL),
	txt("* keepin an EYE on ya, of course. what else?", SOKRATES.NEUTRAL),
	txt("* I... Okay? I don't think I really need anyone else to watch over me.", MERRY.NEUTRAL), 
	txt("* Like just having Renko is perfectly fine.", MERRY.NEUTRAL),
	txt("* Then again, maybe I'm just hallcinating you right now.", MERRY.NEUTRAL),
	txt("* nah man. I'm the real deal. trust me. ya already well aware of the truths you can see, aren't ya?", SOKRATES.NEUTRAL),
	txt("* Yes. Although the fact you know this much about me is kind of disturbing?", MERRY.NEUTRAL),
	txt("* hey now! I'm not a stalker! and I don't know everything about ya either!", SOKRATES.NEUTRAL),
	txt("* like, I don't know what ya social security number is for instance! or ya favorite color!", SOKRATES.NEUTRAL),
	txt("* G-Good???", MERRY.NEUTRAL),
	txt("* And it's purple, for reference.", MERRY.NEUTRAL),
	txt("* ahhhh okie dokie.", SOKRATES.NEUTRAL),
	txt("* oh, and while I'm asking questions here, what is that essay ya writing over there?", SOKRATES.NEUTRAL), 
	txt("* must be boring if you went snoozy-doozy.", SOKRATES.NEUTRAL),
	txt("* Uhm. It's not quite boring, I've just felt really exhausted recently.", MERRY.NEUTRAL), 
	txt("* I've barely slept the past 24 hours.", MERRY.NEUTRAL),
	txt("* ah. that'd explain a few things.", SOKRATES.NEUTRAL),
	txt("* Listen. I promise I'm trying to take care of myself here! It's just...", MERRY.NEUTRAL),
	txt("* This is one of the final essays for my psychology major, and I really want to do it right!", MERRY.NEUTRAL),
	txt("* So it's, well, pretty scary to think of what might happen if I fail it.", MERRY.NEUTRAL),
	txt("* And it's always been on my mind for weeks. It just feels... suffocating, I guess.", MERRY.NEUTRAL),
	txt("* well, maribel hearn. want some of my honest advice? it might help."),
	txt("* Uh... sure.", MERRY.NEUTRAL),
	txt("* well. first off, maybe ya shouldn't be placing your expectations so high, ya know?", SOKRATES.NEUTRAL),
	txt("* don't get me wrong I know it's stressful and all but like.", SOKRATES.NEUTRAL), 
	txt("* maybe you're making a bigger deal out of this than you need to.", SOKRATES.NEUTRAL),
	txt("* I don't know. My future could literally depend on this paper...", MERRY.NEUTRAL),
	txt("* nah. don't sweat it kid, it's not gonna be the end of the world if ya fail.", SOKRATES.NEUTRAL),
	txt("* like, if you asked me, I think it's already pretty obvious you're useless.", SOKRATES.NEUTRAL),
	txt("* so really, what's gonna change?", SOKRATES.NEUTRAL),
	txt("* ...", MERRY.NEUTRAL),
	txt("* I mean, you've always been an utter freak to people.", SOKRATES.NEUTRAL), 
	txt("* and the unlucky few willing to put up with you only just get dragged into your problems.", SOKRATES.NEUTRAL),
	txt("* you hate your own reflection in the mirror, and rightfully so. I'd hate those disgusting eyes of yours too.", SOKRATES.NEUTRAL),
	txt("* pupils that see the void and everything forgotten and everything you want to be and never will be.", SOKRATES.NEUTRAL),
	txt("* pupils that see the one person you love, that you know you're just going to drag down with you.", SOKRATES.NEUTRAL),
	txt("* and you're going to lose them one day. and you're going to hate it.", SOKRATES.NEUTRAL), 
	txt("* you're going to scream and cry and wonder why it all had to end.", SOKRATES.NEUTRAL),
	txt("* and then? you'll be all alone. alone with nothing but your sick, twisted, mi-", SOKRATES.NEUTRAL),
	// bye bye tv lmao
	txt("* ...", MERRY.NEUTRAL),
	txt("* You know, I really thought I buried you awhile ago.", MERRY.NEUTRAL),
	txt("* Maybe it was never that simple...", MERRY.NEUTRAL),
	txt("* Merry?", RENKO.NEUTRAL),
	txt("* O-Oh. Hi, Renko.", MERRY.NEUTRAL),
	txt("* ... Did you happen to uhm, see any of that.", MERRY.NEUTRAL),
	txt("* Not really. I woke up, wondered where you went, and came over to see you...", RENKO.NEUTRAL), 
	txt("* Unplugging our television for some reason?", RENKO.NEUTRAL),
	txt("* But you seem really shaken up. I'm guessing you must have found a boundary there?", RENKO.NEUTRAL), 
	txt("* Usually those don't attach themselves to technology...", RENKO.NEUTRAL),
	txt("* I saw... a spectre of sorts, of times where I wasn't as kind to myself.", MERRY.NEUTRAL),
	txt("* Of times before I met you.", RENKO.NEUTRAL),
	txt("* Do... Do you want to talk about it?", RENKO.NEUTRAL),
	txt("* No. I don't. It's better off being forgotten anyway.", MERRY.NEUTRAL),
	txt("* My self-esteem... isn't as bad as it used to be, and I have you to love.", MERRY.NEUTRAL), 
	txt("* To remind me that I'm loved.", MERRY.NEUTRAL),
	txt("* I don't have to burden myself with all of that baggage anymore.", MERRY.NEUTRAL),
	txt("* You know, Merry. You taught me through our explorations that sometimes...", RENKO.NEUTRAL), 
	txt("* Fantasies really are scary, actually.", RENKO.NEUTRAL),
	txt("* And maybe... Maybe the worst fantasies are the ones we conjure up about ourselves.", RENKO.NEUTRAL),
	txt("* When at the end of the day, we don't have to listen to a voice inside our head telling us we aren't worth something.", RENKO.NEUTRAL),
	txt("* We just have to stay determined to turn our dreams into reality. Like you'd always say.", MERRY.NEUTRAL),
	txt("* Yeah. Exactly.", RENKO.NEUTRAL),
	txt("* And you'll ace that essay, damn it. You know I have your back.", RENKO.NEUTRAL),
	txt("* Thanks, Renko. I'll try my best.", MERRY.NEUTRAL),
	txt("* I know you will.", RENKO.NEUTRAL),
	txt("* Now, let's get back to bed, okay? This essay is tomorrow's problem to worry about now.", RENKO.NEUTRAL),
	txt("* Huh? But-", MERRY.NEUTRAL),
	txt("* No buts! Only cuddles. Cuddles are more important and you know it."),
	txt("* ... Tch. You know me so well.", MERRY.NEUTRAL),
	txt("* Fine. Let's go to bed then.", MERRY.NEUTRAL),
	txt("* And thanks again for checking on me, Renko. I love you.", MERRY.NEUTRAL),
	txt("* Love you too, Merry.", RENKO.NEUTRAL),
	// the end!
	
	];
	
	endevent = function() { // this should send the player back to the title screen instead.
		log("GAME OVER, MAN!");
		game_end();
		//startpattern("Midnight Alarm");
	};
}